export var myArr = [
  {
    phone: [
      {
        cartID: 1,
        productName: "Samsung Galaxy S21",
        img: "./images/product/phone/Samsung_Galaxy_S21.gif",
        price: 3790,
        quantity: 1,
      },
      {
        cartID: 2,
        productName: "Apple iPhone 12 Pro Max",
        img: "./images/product/phone/iphone_pro_max.jpg",
        price: 5000,
        quantity: 1,
      },
      {
        cartID: 3,
        productName: "Apple iPhone 11",
        img: "./images/product/phone/Apple_iPhone_11.gif",
        price: 3590,
        quantity: 1,
      },
      {
        cartID: 4,
        productName: "Samsung Galaxy A72",
        img: "./images/product/phone/Samsung_Galaxy_A72.gif",
        price: 1500,
        quantity: 1,
      },
      {
        cartID: 5,
        productName: "Xiaomi Redmi Note 10",
        img: "./images/product/phone/Xiaomi Redmi Note 10.gif",
        price: 1050,
        quantity: 1,
      },
      {
        cartID: 6,
        productName: "Xiaomi Poco X3 Pro",
        img: "./images/product/phone/Xiaomi Poco X3 Pro.gif",
        price: 1320,
        quantity: 1,
      },
      {
        cartID: 7,
        productName: "Samsung Galaxy A51",
        img: "./images/product/phone/Samsung Galaxy A51.gif",
        price: 1370,
        quantity: 1,
      },
      {
        cartID: 8,
        productName: "Xiaomi Mi 10",
        img: "./images/product/phone/Xiaomi Mi 10.gif",
        price: 1530,
        quantity: 1,
      },
      {
        cartID: 9,
        productName: "Samsung Galaxy Z",
        img: "./images/product/phone/Samsung Galaxy Z.gif",
        price: 2200,
        quantity: 1,
      },
      {
        cartID: 10,
        productName: "Nokia C2-01",
        img: "./images/product/phone/Nokia C2-01.gif",
        price: 279,
        quantity: 1,
      },
      {
        cartID: 11,
        productName: "2017 Nokia",
        img: "./images/product/phone/2017 Nokia.gif",
        price: 117,
        quantity: 1,
      },
      {
        cartID: 12,
        productName: "Apple iPhone XR",
        img: "./images/product/phone/Apple iPhone XR.gif",
        price: 2897,
        quantity: 1,
      },
      {
        cartID: 13,
        productName: "Apple iPhone X",
        img: "./images/product/phone/iPhone X.gif",
        price: 2300,
        quantity: 1,
      },
      {
        cartID: 14,
        productName: "Samsung Galaxy A32",
        img: "./images/product/phone/Samsung Galaxy A32.gif",
        price: 755,
        quantity: 1,
      },
      {
        cartID: 15,
        productName: " Samsung Galaxy A10",
        img: "./images/product/phone/Samsung Galaxy A10.gif",
        price: 224,
        quantity: 1,
      },
    ],
  },
  {
    TV: [
      {
        cartID: 16,
        productName: "Samsung 65″ 4K",
        img: "./images/product/TV/Samsung 65″ 4K.gif",
        price: 2520,
        quantity: 1,
      },
      {
        cartID: 17,
        productName: "Xiaomi 43″ 4K",
        img: "./images/product/TV/Xiaomi 43″ 4K.gif",
        price: 1500,
        quantity: 1,
      },
      {
        cartID: 18,
        productName: "Samsung 43″ 4K",
        img: "./images/product/TV/Samsung 43″ 4K.gif",
        price: 2525,
        quantity: 1,
      },
      {
        cartID: 19,
        productName: "LG 45″ 4K",
        img: "./images/product/TV/LG 45 4K.gif",
        price: 1990,
        quantity: 1,
      },
      {
        cartID: 20,
        productName: "Xiaomi 4K ‏65″",
        img: "./images/product/TV/Xiaomi 4K ‏65.gif",
        price: 3100,
        quantity: 1,
      },
      {
        cartID: 21,
        productName: "LG 65″ 4K‏",
        img: "./images/product/TV/LG 65″ 4K.gif",
        price: 7800,
        quantity: 1,
      },
      {
        cartID: 22,
        productName: "LG 4K 77″",
        img: "./images/product/TV/LG 4K 77″.jpg",
        price: 15990,
        quantity: 1,
      },
      {
        cartID: 23,
        productName: "Samsung 4K ‏50″",
        img: "./images/product/TV/Samsung 4K ‏50″.gif",
        price: 2820,
        quantity: 1,
      },
      {
        cartID: 24,
        productName: "LG 4K ‏43″",
        img: "./images/product/TV/LG 4K ‏43″.gif",
        price: 1900,
        quantity: 1,
      },
      {
        cartID: 25,
        productName: "PHILIPS 58″ 4K",
        img: "./images/product/TV/PHILIPS 58″ 4K.jpg",
        price: 2390,
        quantity: 1,
      },
      {
        cartID: 26,
        productName: "SHARP 4K 70″",
        img: "./images/product/TV/SHARP 4K 70″.jpg",
        price: 3590,
        quantity: 1,
      },
      {
        cartID: 27,
        productName: "TCL FHD 43″",
        img: "./images/product/TV/TCL FHD 43″.jpg",
        price: 1748,
        quantity: 1,
      },
      {
        cartID: 28,
        productName: "Hisense 4K 70″",
        img: "./images/product/TV/Hisense 4K 70″.jpg",
        price: 3990,
        quantity: 1,
      },
      {
        cartID: 29,
        productName: "Haier 42″ LED",
        img: "./images/product/TV/Haier 42″ LED.jpg",
        price: 1416,
        quantity: 1,
      },
      {
        cartID: 30,
        productName: "ELCO 4K 58″",
        img: "./images/product/TV/ELCO 4K 58″.jpg",
        price: 1690,
        quantity: 1,
      },
    ],
  },
  {
    laptop: [
      {
        cartID: 31,
        productName: "Asus Pro P1440FA",
        img: "./images/product/laptop/Asus Pro P1440FA.jpg",
        price: 1690,
        quantity: 1,
      },
      {
        cartID: 32,
        productName: "HP 15-DW2042NJ",
        img: "./images/product/laptop/HP 15-DW2042NJ.png",
        price: 2490,
        quantity: 1,
      },
      {
        cartID: 33,
        productName: "Lenovo IdeaCentre AIO",
        img: "./images/product/laptop/Lenovo IdeaCentre AIO.png",
        price: 3790,
        quantity: 1,
      },
      {
        cartID: 34,
        productName: "Lenovo IdeaPad Flex 5",
        img: "./images/product/laptop/Lenovo IdeaPad Flex 5.png",
        price: 2690,
        quantity: 1,
      },
      {
        cartID: 35,
        productName: "Apple MacBook Pro 13",
        img: "./images/product/laptop/Apple MacBook Pro 13.webp",
        price: 6345,
        quantity: 1,
      },
      {
        cartID: 36,
        productName: "Asus ZenBook UM425UA",
        img: "./images/product/laptop/Asus ZenBook UM425UA.jpg",
        price: 4199,
        quantity: 1,
      },
      {
        cartID: 37,
        productName: "Asus VivoBook X413EA",
        img: "./images/product/laptop/Asus VivoBook X413EA.jpg",
        price: 2900,
        quantity: 1,
      },
      {
        cartID: 38,
        productName: "HP Laptop 14S-DQ2006NJ",
        img: "./images/product/laptop/HP Laptop 14S-DQ2006NJ.gif",
        price: 2679,
        quantity: 1,
      },
      {
        cartID: 39,
        productName: "HP Pavilion 14",
        img: "./images/product/laptop/HP Pavilion.jpg",
        price: 3390,
        quantity: 1,
      },
      {
        cartID: 40,
        productName: "Acer TravelMate P2",
        img: "./images/product/laptop/Acer TravelMate P2.jpg",
        price: 2990,
        quantity: 1,
      },
      {
        cartID: 41,
        productName: "Apple MacBook Pro 16",
        img: "./images/product/laptop/Apple MacBook Pro 16.jpg",
        price: 8499,
        quantity: 1,
      },
      {
        cartID: 42,
        productName: "Dell Inspiron 15 3000",
        img: "./images/product/laptop/Dell Inspiron 15 3000.jpg",
        price: 2090,
        quantity: 1,
      },
      {
        cartID: 43,
        productName: "Lenovo ThinkPad E15",
        img: "./images/product/laptop/Lenovo ThinkPad E15.jpg",
        price: 4190,
        quantity: 1,
      },
      {
        cartID: 44,
        productName: "Lenovo ThinkPad X1",
        img: "./images/product/laptop/Lenovo ThinkPad X1.jpg",
        price: 8190,
        quantity: 1,
      },
      {
        cartID: 45,
        productName: "Dell G5 15 Gaming",
        img: "./images/product/laptop/Dell G5 15 Gaming.jpg",
        price: 6549,
        quantity: 1,
      },
    ],
  },
];
